### ISSUE TITLE
Something about the visualization

### ISSUE THREAD

**Issue by OuyangJunyuan** [dschinagl/occam#1]
The visualization result in paper are beautiful! Is these figures(eg: Fig .1 in paper)  were drawn by Open3D visualization tool(seems not) or something others? Looking forward to your reply：)

**Comment by dschinagl** [comment]
You are right, we created the visualizations in the paper using a rendering tool.
An example of a point cloud renderer can be found here:
https://github.com/tolgabirdal/Mitsuba2PointCloudRenderer

**Comment by OuyangJunyuan** [comment]
> 

awesome! by dong this, i can also have a better visualization effect!!!
