### ISSUE TITLE
Point dropping evaluation questions

### ISSUE THREAD

**Issue by KexuanXia** [dschinagl/occam#10]
Hi,

thank you for your excellent work again. I have some questions about Fig. 6 Point dropping evaluation. Please help me with it.

1. Does the mean confidence score in Fig. 6 mean the average confidence scores obtained after dropping points on the whole KITTI evaluation dataset? This means one has to go through all the detections and corresponding attribution maps in more than 3000 scenes to get point dropping evaluation?
2. Why does it start at 1.0? I think it should be slightly lower than 1.0. Because even if we don't drop any points, the original confidence scores are always lower than 1.0. 
![image](https://github.com/user-attachments/assets/499a6d03-64a0-4aa4-ae72-bcb7494af60a)

**Comment by dschinagl** [comment]
Hi, 

yes, but as mentioned in the paper, we limited the evaluation to the points inside the bounding box, so the evaluation can be done in parallel for all detections in a scene.

We used the initial confidence score of a detection as 100%, i.e. 1.0, to ensure that uncertain detections with low scores do not change the overall evaluation outcome.

Hope this helps,
best regards
David

**Comment by KexuanXia** [comment]
Hi, David

thank you for your reply, it's really helpful.

Best Regards,
Kexuan
