### ISSUE TITLE
when model gets no bounding box, there will be an error in computing iou

### ISSUE THREAD

**Issue by zhangtingyu11** [dschinagl/occam#5]
when model gets no bounding box, there will be an error in computing iou, how do you solve it?
Exception has occurred: RuntimeError
CUDA error: invalid configuration argument
  File "/home/zty/Project/DeepLearning/SASA/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 76, in boxes_iou3d_gpu
    vol_a = (boxes_a[:, 3] * boxes_a[:, 4] * boxes_a[:, 5]).view(-1, 1)
  File "/home/zty/Project/DeepLearning/SASA/tools/occam_demo.py", line 80, in main
    iou = boxes_iou3d_gpu(pred_boxes, gt_boxes)
  File "/home/zty/Project/DeepLearning/SASA/tools/occam_demo.py", line 126, in <module>
    main()

**Comment by dschinagl** [comment]
Hi,
yes, the prerequisite is that the model recognizes an object in the entire point cloud that can be analyzed.
This is just a demonstration example.
If the base_det is already empty in your case, you can stop there:
https://github.com/dschinagl/occam/blob/9a3c0900f3d6172a8622cdce10a83e769ad3acbb/occam_demo.py#L49
Best regards

**Comment by zhangtingyu11** [comment]
> Hi, yes, the prerequisite is that the model recognizes an object in the entire point cloud that can be analyzed. This is just a demonstration example. If the base_det is already empty in your case, you can stop there:
> 
> https://github.com/dschinagl/occam/blob/9a3c0900f3d6172a8622cdce10a83e769ad3acbb/occam_demo.py#L49
> 
> 
> Best regards

Thank you for your reply and your awesome work! Best wishes
