### ISSUE TITLE
visualization only one target

### ISSUE THREAD

**Issue by Bryceder** [dschinagl/occam#7]
"Hello, may I ask why the demo can only produce a visualization for one target during runtime? If I want to display all the targets in a single frame of point cloud, how should I proceed?"

**Comment by dschinagl** [comment]
Hi,
for each detection, a separate attribution map is generated that visualizes the importance of all points, including the importance of points outside the bounding box. Therefore, only a single attribution map, in this case for the first detection, can be displayed at the same time.
Best regards
David
